# Generated by Django 4.0.2 on 2022-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='whatsapp',
            field=models.CharField(max_length=40, null=True, verbose_name='WhatsApp'),
        ),
    ]
