# Generated by Django 4.0.2 on 2022-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_bigbanner_subtitleicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тема')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='topics',
            field=models.ManyToManyField(to='news.Topic', verbose_name='Темы'),
        ),
    ]
